# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nateh\PycharmProjects\pyChatClient\pyChat_loginScreen_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginScreen_MainWindow(object):
    def setupUi(self, loginScreen_MainWindow):
        loginScreen_MainWindow.setObjectName("loginScreen_MainWindow")
        loginScreen_MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(loginScreen_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 150, 441, 151))
        self.label.setObjectName("label")
        loginScreen_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(loginScreen_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        loginScreen_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(loginScreen_MainWindow)
        self.statusbar.setObjectName("statusbar")
        loginScreen_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(loginScreen_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(loginScreen_MainWindow)

    def retranslateUi(self, loginScreen_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        loginScreen_MainWindow.setWindowTitle(_translate("loginScreen_MainWindow", "MainWindow"))
        self.label.setText(_translate("loginScreen_MainWindow", "Test"))
