# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nateh\PycharmProjects\pyChatClient\pyChat_loginScreen_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginScreen_MainWindow(object):
    def setupUi(self, loginScreen_MainWindow):
        loginScreen_MainWindow.setObjectName("loginScreen_MainWindow")
        loginScreen_MainWindow.resize(550, 550)
        loginScreen_MainWindow.setStyleSheet("#centralWidget {\n"
" background: rgba(32, 80, 96, 100);\n"
" }\n"
"\n"
"#topPanel { \n"
"background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0, y2:0, stop:0 rgba(91, 204, 233, 100), stop:1 rgba(32, 80, 96, 100));\n"
" }\n"
"\n"
"#loginForm\n"
"{\n"
" background: rgba(0, 0, 0, 80);\n"
" border-radius: 8px;\n"
"}\n"
"\n"
"QLabel { color: white; }\n"
"\n"
"QLineEdit { border-radius: 3px; }\n"
"\n"
"QPushButton\n"
"{\n"
"  color: white;\n"
"  background-color: #27a9e3;\n"
"  border-width: 0px;\n"
"  border-radius: 3px;\n"
"}\n"
"\n"
"QPushButton:hover { background-color: #66c011; }\n"
"\n"
"#centralWidget\n"
"{\n"
"  background: rgba(32, 80, 96, 100);\n"
"  border-image: url(:/images/resources/images/6204882.jpg);\n"
"}")
        self.centralWidget = QtWidgets.QWidget(loginScreen_MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topPanel = QtWidgets.QWidget(self.centralWidget)
        self.topPanel.setObjectName("topPanel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topPanel)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.currentDateTime_label = QtWidgets.QLabel(self.topPanel)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.currentDateTime_label.setFont(font)
        self.currentDateTime_label.setText("")
        self.currentDateTime_label.setObjectName("currentDateTime_label")
        self.horizontalLayout.addWidget(self.currentDateTime_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.exitButton = QtWidgets.QPushButton(self.topPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setMinimumSize(QtCore.QSize(35, 35))
        self.exitButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon)
        self.exitButton.setIconSize(QtCore.QSize(20, 20))
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton)
        self.verticalLayout.addWidget(self.topPanel)
        self.spacer_3 = QtWidgets.QHBoxLayout()
        self.spacer_3.setContentsMargins(-1, 0, -1, -1)
        self.spacer_3.setObjectName("spacer_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.spacer_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.spacer_3)
        self.middlePanel = QtWidgets.QHBoxLayout()
        self.middlePanel.setContentsMargins(-1, 0, -1, 0)
        self.middlePanel.setObjectName("middlePanel")
        self.logo_label = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_label.sizePolicy().hasHeightForWidth())
        self.logo_label.setSizePolicy(sizePolicy)
        self.logo_label.setMinimumSize(QtCore.QSize(150, 150))
        self.logo_label.setStyleSheet("border: 1px solid;\n"
"\n"
"  border-image: url(:/images/resources/images/pumpkin-pie.png);")
        self.logo_label.setText("")
        self.logo_label.setScaledContents(False)
        self.logo_label.setObjectName("logo_label")
        self.middlePanel.addWidget(self.logo_label)
        self.verticalLayout.addLayout(self.middlePanel)
        self.spacer_2 = QtWidgets.QHBoxLayout()
        self.spacer_2.setContentsMargins(-1, 0, -1, -1)
        self.spacer_2.setObjectName("spacer_2")
        spacerItem2 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.spacer_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.spacer_2)
        self.bottomPanel = QtWidgets.QHBoxLayout()
        self.bottomPanel.setContentsMargins(0, 0, -1, -1)
        self.bottomPanel.setObjectName("bottomPanel")
        self.loginForm = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginForm.sizePolicy().hasHeightForWidth())
        self.loginForm.setSizePolicy(sizePolicy)
        self.loginForm.setMinimumSize(QtCore.QSize(300, 250))
        self.loginForm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.loginForm.setStyleSheet("#loginForm_verticalWidget { border: 1px solid; }")
        self.loginForm.setObjectName("loginForm")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.loginForm)
        self.verticalLayout_2.setContentsMargins(35, 35, 35, 25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.username_lineEdit = QtWidgets.QLineEdit(self.loginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_lineEdit.sizePolicy().hasHeightForWidth())
        self.username_lineEdit.setSizePolicy(sizePolicy)
        self.username_lineEdit.setMinimumSize(QtCore.QSize(200, 25))
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.horizontalLayout_6.addWidget(self.username_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.password_lineEdit = QtWidgets.QLineEdit(self.loginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_lineEdit.sizePolicy().hasHeightForWidth())
        self.password_lineEdit.setSizePolicy(sizePolicy)
        self.password_lineEdit.setMinimumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setCursorPosition(0)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.horizontalLayout_5.addWidget(self.password_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.login_pushButton = QtWidgets.QPushButton(self.loginForm)
        self.login_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.login_pushButton.setObjectName("login_pushButton")
        self.verticalLayout_2.addWidget(self.login_pushButton)
        self.registerButton = QtWidgets.QPushButton(self.loginForm)
        self.registerButton.setMinimumSize(QtCore.QSize(0, 25))
        self.registerButton.setObjectName("registerButton")
        self.verticalLayout_2.addWidget(self.registerButton)
        self.forgotPasswordButton = QtWidgets.QPushButton(self.loginForm)
        self.forgotPasswordButton.setMinimumSize(QtCore.QSize(0, 25))
        self.forgotPasswordButton.setObjectName("forgotPasswordButton")
        self.verticalLayout_2.addWidget(self.forgotPasswordButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.connectionStatusLabel = QtWidgets.QLabel(self.loginForm)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.connectionStatusLabel.setFont(font)
        self.connectionStatusLabel.setText("")
        self.connectionStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.connectionStatusLabel.setObjectName("connectionStatusLabel")
        self.verticalLayout_2.addWidget(self.connectionStatusLabel)
        self.bottomPanel.addWidget(self.loginForm)
        self.verticalLayout.addLayout(self.bottomPanel)
        self.spacer = QtWidgets.QHBoxLayout()
        self.spacer.setContentsMargins(-1, 0, -1, -1)
        self.spacer.setObjectName("spacer")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.spacer.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.spacer)
        loginScreen_MainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(loginScreen_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.menubar.setObjectName("menubar")
        loginScreen_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(loginScreen_MainWindow)
        self.statusbar.setObjectName("statusbar")
        loginScreen_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(loginScreen_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(loginScreen_MainWindow)

    def retranslateUi(self, loginScreen_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        loginScreen_MainWindow.setWindowTitle(_translate("loginScreen_MainWindow", "MainWindow"))
        self.login_pushButton.setText(_translate("loginScreen_MainWindow", "Login"))
        self.registerButton.setText(_translate("loginScreen_MainWindow", "Register"))
        self.forgotPasswordButton.setText(_translate("loginScreen_MainWindow", "Forgot Password?"))
import resources_rc
